tap "homebrew/bundle"
tap "homebrew/core"
tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "awscli"
brew "bat"
brew "bats-core"
brew "coreutils"
brew "lotyp/formulae/dockutil"
brew "mackup"
brew "nano"
brew "stow"
brew "thefuck"
brew "topgrade"

# fs/network
brew "bat"
brew "croc"
brew "httpie"
brew "ngrok"
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "wget"
brew "zoxide"

# search/grep/diff
brew "diff-so-fancy"
brew "difftastic"

# brew "dockutil" // done by a custom install temporarily while dockutil homebrew issue is resolved
# brew install 'hpedrorodrigues/tools/dockutil'

brew "fasd"
brew "fd"
brew "fzf"
brew "gnu-sed"
brew "grep"
brew "jq"
brew "nvm"
brew "pandoc"
brew "peco"
brew "psgrep"
brew "rg"
brew "zellij"

# languages/tools
brew "fnm"
brew "gh"
brew "python"
brew "rust"
brew "shellcheck"

# media
brew "ffmpeg"
brew "imagemagick"
brew "ssh-copy-id"
brew "stow"
brew "ripgrep"
brew "topgrade"
brew "tree"
brew "unar"
brew "webp"

# misc
brew "grip"
